version: '3'

services:
  facefood-postgres-compose:
    image: postgres
    env_file:
      - .env # configure postgres
    ports:
      - '15432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  facefood-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '16543:80'
    depends_on:
      - facefood-postgres-compose

volumes:
  database-data: # named volumes can be managed easier using docker-compose

